sudo: false
language: node_js
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - os: windows
cache:
  directories:
  - node_modules
node_js:
- '10'
- '9'
- '8'
- '7'
- '6'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/