sudo: false
language: node_js
os:
  - linux
  - osx
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: dBV+r1iCGd/aLC5IczQ+f6z8Dnv4Ch7CJot/Oz5eILXXDSY8FmCicILYNSI8NEBNcQa+kPdQDC3vk6CNS9jXYBTmTaHHDcZ7o969JRWIfwkzRX0nnO0wrNqHuKsJaIU/5BsvLSvAeuA/DEmyAww1d2JCEWKY/mv2niuHdhs89nopwfcZduF+QYv+XrxZcTnQYrV/Xa77YOHCovA6XfPrggOqOPa6gn+/BxrF8GCTOgEu07X9dtKuGEahgacwiBYQaaPmeGwx4RFwW6MPhyAtRpBwMvrjGQR+Y6LRDQ5Dx26ddUNBBFVGfeIApF/WlbyPQDYaSGmvTS85I30sG2qElNO5iTfSKepDfmBKvXu6YSwgjnfqYpMkaaWTtqPWcqIEDSyyzLxZtIkz+AgzibHFMU0IWPRWg64EemKLy0SoFTrX7C7mHJdB7C9AtiohvnN+Zh7e9lAp+jVAhGKk4Zw2EVUCuy4vgZZo0E6NRgOs0uC7s2oQZpOv2AXRyFRYp+dOdMB71Srs0n/h3OoQdmC6w4teiAwY6BU6Caj7fAcO0MHq43XvyEa+CdvSwGLM2j2U8XfierPDH+LaIhWd34402pF9QBPqSDNXS+Blpt3iTQjvovzSNFjYQxuJG8hkAx7EnGLYAospSx3oEc/URjuvZJccsLjSNByhfu9oIsc07M8=
node_js:
- '6'
- '5'
- '4'
- iojs-v3
- iojs-v2
- iojs-v1
- '0.12'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
after_success:
- curl -Lo travis_after_all.py https://git.io/travis_after_all
- python travis_after_all.py
- export $(cat .to_export_back) &> /dev/null
- npm run semantic-release
after_script:
- ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
addons:
  code_climate:
    repo_token: 76a681d36b613129970598a0b0cb1a271beb27c4faba8c3f216648b8f5601622
