# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
init:
  - git config --global core.autocrlf true

# build version format
version: "{build}"

# what combinations to test
environment:
  matrix:
    - nodejs_version: "8"
    
platform:
  - x64

# Get the stable version of node
install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g npm
  - npm i

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test

cache:
  - node_modules -> package.json
